# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
