# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='arquivo',
            field=models.FileField(default=0, upload_to=media.models.get_file_path, verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
